import turtle
apals = turtle.Turtle()
apals.fillcolor("#170c2e")
apals.begin_fill()
apals.color("#170c2e")
apals.up()
apals.setpos(10, -10)
apals.down()
apals.circle (70)
apals.end_fill()

trissturis = turtle.Turtle()
trissturis.fillcolor("#187f96")
trissturis.begin_fill()
trissturis.color("#187f96")
trissturis.up()
trissturis.setpos(-70, -40)
trissturis.down()
trissturis.circle(30, steps =3)
trissturis.end_fill()

rombs = turtle.Turtle()
rombs.fillcolor("#3f9931")
rombs.begin_fill()
rombs.color("#3f9931")
rombs.up()
rombs.setpos(70, 50)
rombs.down()
rombs.circle(40,steps = 4)
rombs.end_fill()